apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: desafio-sre-app
 
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/kleberadesouza/desafio-sre-manifesto.git 
    targetRevision: HEAD
    path: . 
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true