apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-sre-app
  labels:
    app: desafio-sre-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio-sre-app
  template:
    metadata:
      labels:
        app: desafio-sre-app
    spec:
      containers:
      - name: app
        
        image: 027922993398.dkr.ecr.us-east-1.amazonaws.com/desafio-sre-app:v3
        ports:
        - containerPort: 8080 
        env:
        
        
        - name: POSTGRES_HOST 
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
        - name: POSTGRES_USER 
          valueFrom:
            secretKeyRef:
              name: bd-credentials
              key: DB_USER       
        - name: POSTGRES_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: bd-credentials
              key: DB_PASSWORD   
              
       
        - name: REDIS_HOST 
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: redis_endpoint

        
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: kafka_brokers