apiVersion: v1
kind: Service
metadata:
  name: desafio-sre-service
spec:
  selector:
    app: desafio-sre-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080 
  type: LoadBalancer 